# syntax=docker/dockerfile:1

FROM node:16-alpine

# Curl is used in cron batch file.
RUN apk --no-cache add curl

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --production --silent

COPY . .

COPY scheduled/crontab /var/spool/cron/crontabs/root
RUN which crond && \
  rm -rf /etc/periodic && \
  chmod 0744 scheduled/entrypoint.sh

EXPOSE 3000

CMD ["node", "bin/www"]
