root: true
env:
  es2021: true
extends:
  - standard
  - prettier
overrides:
  - files:
      - "*.js"
      - "express/bin/www"
    excludedFiles: "express/public"
    env:
      node: true
  - files: "express/public/javascripts/*.js"
    env:
      browser: true
rules:
  no-console: error
