INSERT INTO domain_primary (name_sl, name_en, udk_code, cerif_name, cerif_code, eurovoc_name, eurovoc_code)
VALUES
  ('Agronomija', 'Agronomy', '63', 'Agronomija', 'B 006', 'Agriculture, forestry and fisheries', '56'),
  ('Arheologija', 'Archeology', '902', 'Arheologija', 'H 340', 'Natural and applied sciences', '3606'),
  ('Arhitektura', 'Architecture', '72', 'Arhitektura, oblikovanje notranjosti', 'T 240', 'Humanities', '3611'),
  ('Astronomija', 'Astronomy', '52', 'Astronomija', 'P 007', 'Natural and applied sciences', '3606'),
  ('Bibliotekarstvo in informacijska znanost', 'Librarianship and information science', '02', 'Dokumentalistika, informacijska znanost, bibliotekarstvo, arhivistika', 'H 100', 'Information and information processing', '3231'),
  ('Biologija', 'Biology', '57', 'Zgodovina in filozofija biomedicinskih ved, teoretična biologija, splošni vidiki evolucije', 'B 100', 'Natural and applied sciences', '3606'),
  ('Biotehnologija', 'Biotechnology', '60', 'Biotehnologija', 'T 490', 'Natural and applied sciences', '3606'),
  ('Botanika', 'Botany', '58', 'Botanika', 'B 004', 'Natural and applied sciences', '3606'),
  ('Družboslovje', 'Social science', '30', 'Družboslovje', 'S 000', 'Social questions', '28'),
  ('Ekonomija', 'Economy', '33', 'Ekonomija, ekonometrija, ekonomska teorija, ekonomski sistemi, ekonomska politika', 'S 180', 'Economics', '16'),
  ('Elektrotehnika', 'Electrical engineering', '621.3', 'Elektronika in elektriška tehnologija', 'T 001', 'Electronics and electrical engineering', '6826'),
  ('Energetika in energija', 'Energetics and energy', '620', 'Energijske raziskave', 'T 140', 'Energy', '66'),
  ('Etnologija in antropologija', 'Ethnology and anthropology', '39', 'Kulturna antropologija, etnologija', 'S 220', 'Humanities', '3611'),
  ('Farmacija', 'Pharmacy', '615', 'Farmakološke vede, farmakognozija, farmacija, toksikologija', 'B 740', 'Health', '2841'),
  ('Filmska umetnost', 'Film arts', '791', 'Dramska umetnost', 'H 330', 'Culture and religion', '2831'),
  ('Filozofija', 'Philosophy', '1', 'Filozofija', 'H 001', 'Humanities', '3611'),
  ('Finance in bančništvo', 'Finance and banking', '336', 'Finančna veda', 'S 181', 'Finance', '24'),
  ('Fizika', 'Physics', '53', 'Fizika', 'P 002', 'Natural and applied sciences', '3606'),
  ('Fotografija', 'Photography', '77', 'Upodabljanje, obdelava podob', 'T 111', 'Culture and religion', '2831'),
  ('Geodezija', 'Geodesy', '528', 'Geodezija', 'P 515', 'Natural and applied sciences', '3606'),
  ('Geografija', 'Geography', '91', 'Fizična geografija, geomorfologija, pedologija, kartografija, klimatologija', 'P 510', 'Natural and applied sciences', '3606'),
  ('Geologija in seizmologija', 'Geology and seismology', '55', 'Geologija, fizična geografija', 'P 005', 'Natural and applied sciences', '3606'),
  ('Glasba', 'Music', '78', 'Muzikologija', 'H 320', 'Culture and religion', '2831'),
  ('Gledališče', 'Theater', '792', 'Dramska umetnost', 'H 330', 'Culture and religion', '2831'),
  ('Gozdarstvo in lesarstvo', 'Forestry and wood industry', '630', 'Gozdarstvo, gozdovi, gozdarska tehnologija', 'B 430', 'Forestry', '5636'),
  ('Gradbeništvo', 'Building industry', '624', 'Gradbeništvo, hidravlika, priobalna tehnologija, mehanika zemljin', 'T 220', 'Building and public works', '6831'),
  ('Javna uprava in delovanje države', 'Public administration and state governing', '35', 'Državno pravo', 'S 140', 'Politics', '4'),
  ('Jezikoslovje', 'Linguistics', '80', 'Jezikoslovje', 'H 350', 'Humanities', '3611'),
  ('Kemija', 'Chemistry', '54', 'Kemija', 'P 003', 'Natural and applied sciences', '3606'),
  ('Književnost', 'Literature', '82', 'Splošna in primerjalna književnost, literarna kritika, literarna teorija', 'H 390', 'Culture and religion', '2831'),
  ('Likovna umetnost', 'Fine Arts', '73/76', 'Slikarstvo', 'H 311', 'Culture and religion', '2831'),
  ('Matematika', 'Mathematics', '51', 'Matematika', 'P 001', 'Natural and applied sciences', '3606'),
  ('Medicina in zdravstvo', 'Medicine and health system', '61', 'Medicina (človek in vretenčarji)', 'B 007', 'Health', '2841'),
  ('Metalurgija', 'Metalurgy', '669', 'Kovinska tehnologija, metalurgija, kovinski izdelki', 'T 450', 'Iron, steel and other metal industries', '6816'),
  ('Meteorologija', 'Meteorology', '551', 'Geofizika, fizična oceanografija, meteorologija', 'P 500', 'Natural and applied sciences', '3606'),
  ('Mikrobiologija', 'Microbiology', '579', 'Mikrobiologija, bakteriologija, virologija, mikologija', 'B 230', 'Natural and applied sciences', '3606'),
  ('Naravoslovje', 'Natural science', '5', 'Naravoslovno-matematične vede', 'P 000', 'Natural and applied sciences', '3606'),
  ('Novinarstvo in mediji', 'Journalism and media', '070', 'Tisk in komunikacijske vede', 'S 265', 'Communications', '3226'),
  ('Oblačila in moda', 'Clothes and fashion', '646/67', 'Tekstilna tehnologija', 'T 470', 'Culture and religion', '2831'),
  ('Obrt in rokodelstvo', 'Craft industry and handicraft', '67', 'Tehnologija ostalih izdelkov', 'T 480', 'Miscellaneous industries', '6846'),
  ('Odnosi z javnostmi', 'Public relations', '354', 'Tisk in komunikacijske vede', 'S 265', 'Marketing', '2031'),
  ('Okoljevarstvo', 'Ecology', '502', 'Okoljska tehnologija, nadzor onesnaženja', 'T 270', 'Environment', '52'),
  ('Paleontologija', 'Palaeontology', '56', 'Paleontologija', 'P 006', 'Natural and applied sciences', '3606'),
  ('Politika in politične vede', 'Politics and political science', '32', 'Politične in upravne vede', 'S 170', 'Politics', '4'),
  ('Pravo', 'Law', '34', 'Pravo', 'S 110', 'Law', '12'),
  ('Prevajanje', 'Translation', '81', 'Teorija prevajanja', 'H 365', 'Miscellaneous industries', '6846'),
  ('Promet in vozila', 'Transport and vehicles', '656', 'Transportna tehnologija', 'T 003', 'Transport', '48'),
  ('Psihologija', 'Psychology', '159.9', 'Psihologija', 'S 260', 'Humanities', '3611'),
  ('Računalništvo in informatika', 'Computer and Information Science', '004', 'Računalništvo, numerična analiza, sistemi, kontrola', 'P 170', 'Information technology and data processing', '3236'),
  ('Rudarstvo', 'Mining industries', '622', 'Rudarstvo', 'T 340', 'Coal and mining industries', '6611'),
  ('Socialno delo', 'Social work', '36', 'Družbeni problemi in blagostanje, socialno skrbstvo', 'S 215', 'Social affairs', '2826'),
  ('Sociologija', 'Sociology', '316', 'Sociologija', 'S 210', 'Humanities', '3611'),
  ('Strojništvo', 'Mechanical engineering', '621', 'Strojništvo, hidravlika, vakuumska tehnologija, vibracije in akustično inženirstvo', 'T 210', 'Mechanical engineering', '6821'),
  ('Šport in igre', 'Sports and games', '796/799', 'Telesna kultura, motorično učenje, šport', 'S 273', 'Social affairs', '2826'),
  ('Trgovina', 'Trade', '339', 'Tržna in industrijska ekonomika', 'S 185', 'Trade', '2016'),
  ('Turizem', 'Tourism', '338', 'Družbena geografija', 'S 230', 'Social affairs', '2826'),
  ('Umetnost in umetnostna zgodovina', 'Arts and art history', '7', 'Umetnostna zgodovina', 'H 310', 'Culture and religion', '2831'),
  ('Urbanizem', 'Urban study', '711', 'Prostorsko planiranje', 'T 260', 'Construction and town planning', '2846'),
  ('Varnost, zaščita in reševanje', 'Safety, protection and rescue', '614', 'Varnostna tehnologija', 'T 500', 'Politics and public safety', '431'),
  ('Verstva in teologija', 'Religion and theology', '2', 'Teologija', 'H 002', 'Culture and religion', '2831'),
  ('Vojaška in obveščevalna dejavnost', 'Army and intelligence', '355', 'Vojaška veda in tehnologija', 'T 330', 'Defence', '821'),
  ('Vzgoja in izobraževanje', 'Education and schooling', '37', 'Pedagogika in didaktika', 'S 270', 'Education', '3206'),
  ('Zavarovalništvo', 'Insurance', '347', 'Zakon o zavarovanjih', 'S 137', 'Insurance', '2431'),
  ('Zgodovina', 'History', '93/94', 'Zgodovina in umetnost', 'H 003', 'Humanities', '3611'),
  ('Zoologija', 'Zoology', '59', 'Zoologija', 'B 005', 'Natural and applied sciences', '3606'),
  ('Zootehnika in veterina', 'Zootechnics and veterinary medicine', '636', 'Zootehnika, živinoreja, vzreja', 'B 400', 'Health', '2841'),
  ('Živilstvo in kulinarika', 'Food industry and culinary', '641', 'Tehnologija hrane in pijač', 'T 430', 'Foodstuff', '6026'),
  ('Neopredeljeno', 'Undefined', '', '', '', '', '');
