INSERT INTO domain_secondary (name_sl, name_en, approved)
VALUES
	('aerobatika', 'aerobatics', TRUE),
	('aerobika', 'aerobics', TRUE),
	('aikido', 'aikido', FALSE),
	('airsoft', 'airsoft', FALSE),
	('alpinizem', 'mountaineering', TRUE),
	('alpska kombinacija', 'alpine combination', FALSE),
	('alpsko smučanje', 'alpine skiing', FALSE),
	('ameriški nogomet', 'American football', FALSE),
	('atletika', 'athletics', TRUE),
	('badminton', 'badminton', TRUE),
	('balinanje', 'bowling', FALSE),
	('balonarstvo', 'ballooning', FALSE),
	('bejzbol', 'baseball', FALSE),
	('biatlon', 'biathlon', TRUE),
	('bilijard', 'billiards', FALSE),
	('bob', 'bob', FALSE),
	('bodibilding', 'bodybuilding', FALSE),
	('boks', 'boxing', TRUE),
	('borilni športi', 'martial arts', FALSE),
	('bowling', 'bowling', FALSE),
	('bungee jumping', 'bungee jumping', FALSE),
	('cestno kolesarstvo', 'road cycling', FALSE),
	('curling', 'curling', FALSE),
	('deskanje', 'surfing', TRUE),
	('deskanje na snegu', 'snowboarding', FALSE),
	('dirka s čolni', 'boat race', FALSE),
	('dirka z avtomobili', 'car race', FALSE),
	('dirka z motorji', 'motorcycle race', FALSE),
	('dirkališčno kolesarstvo (velodrom)', 'racing cycling (velodrome)', FALSE),
	('dresurno jahanje', 'dressage riding', TRUE),
	('drsanje in rolanje', 'skating and rollerblading', FALSE),
	('dviganje uteži', 'weight lifting', TRUE),
	('džu džitsu', 'ju jitsu', FALSE),
	('ekstremni športi', 'extreme sports', FALSE),
	('floorball', 'floorball', FALSE),
	('formula 1', 'formula 1', FALSE),
	('gimnastika', 'gymnastics', TRUE),
	('golf', 'golf', TRUE),
	('gorništvo', 'mountaineering', FALSE),
	('gorsko kolesarstvo', 'mountain biking', FALSE),
	('hitra hoja', 'brisk walking', TRUE),
	('hitrostno drsanje', 'speed skating', TRUE),
	('hitrostno potapljanje in plavanje s plavutmi', 'speed diving and fin swimming', FALSE),
	('hokej na kotalkah', 'roller hockey', FALSE),
	('hokej na ledu', 'ice hockey', TRUE),
	('hokej na rolerjih', 'roller hockey', FALSE),
	('hokej na travi', 'field hockey', FALSE),
	('jadralno letalstvo', 'gliding', FALSE),
	('jadralno padalstvo', 'paragliding', FALSE),
	('jadralstvo', 'sailing', FALSE),
	('jamarstvo', 'caving', FALSE),
	('judo', 'judo', TRUE),
	('kajakaštvo', 'kayaking', TRUE),
	('karate', 'karate', TRUE),
	('karting', 'karting', FALSE),
	('kasaštvo', 'kasachstvo', FALSE),
	('kegljanje', 'bowling', FALSE),
	('kendo', 'kendo', FALSE),
	('kmečki biljard', 'peasant billiards', FALSE),
	('kockboxing', 'kockboxing', FALSE),
	('kolesarstvo', 'cycling', TRUE),
	('košarka', 'basketball', TRUE),
	('kriket', 'cricket', FALSE),
	('kros', 'cross', FALSE),
	('kung-fu', 'kung fu', FALSE),
	('lacrosse', 'lacrosse', FALSE),
	('lokostrelstvo', 'archery', TRUE),
	('maraton', 'marathon', TRUE),
	('met diska', 'with disk', TRUE),
	('met kladiva', 'hammer throw', TRUE),
	('met kopja', 'javelin throw', TRUE),
	('metanje podkve', 'throwing a horseshoe', FALSE),
	('meti', 'target', FALSE),
	('modelarstvo', 'modeling', FALSE),
	('motokros', 'motocross', TRUE),
	('motorizirani športi', 'motorized sports', FALSE),
	('namizni nogomet', 'table football', FALSE),
	('namizni tenis', 'table tennis', FALSE),
	('nogomet', 'football', TRUE),
	('nordijska kombinacija', 'Nordic combination', TRUE),
	('nordijsko smučanje', 'Nordic skiing', FALSE),
	('odbojka', 'volleyball', TRUE),
	('odbojka na mivki', 'beach volleyball', TRUE),
	('orientacija', 'orientation', FALSE),
	('padalstvo', 'parachuting', FALSE),
	('paeyball', 'paeyball', FALSE),
	('paintball', 'paintball', FALSE),
	('paralelni slalom', 'parallel slalom', FALSE),
	('pasja dirka', 'dog race', FALSE),
	('petanke', 'petanque', FALSE),
	('petelinja bitka', 'rooster battle', FALSE),
	('pikado', 'darts', FALSE),
	('plavanje', 'swimming', TRUE),
	('podvodni hokej', 'underwater hockey', FALSE),
	('polaganje rok', 'laying hands', FALSE),
	('polo', 'polo', FALSE),
	('potapljaštvo', 'diving', FALSE),
	('preskakovanje ovir', 'jumping over obstacles', FALSE),
	('ritmična gimnastika', 'rhythmic gymnastics', TRUE),
	('rokoborba', 'wrestling', TRUE),
	('rokomet', 'handball', TRUE),
	('rolanje', 'rollerblading', FALSE),
	('rolkanje', 'skateboarding', FALSE),
	('rugby', 'rugby', TRUE),
	('sabljanje', 'fencing', TRUE),
	('sankanje', 'sledding', TRUE),
	('savate', 'savate', FALSE),
	('sinhrono plavanje', 'synchronous swimming', TRUE),
	('skok ob palici', 'pole vault', TRUE),
	('skok v višino', 'high jump', TRUE),
	('skoki', 'jumps', FALSE),
	('skoki v vodo', 'jumps into the water', FALSE),
	('skoki v vodo z velikih višin', 'jumping into the water from great heights', FALSE),
	('skupinski športi', 'group sports', FALSE),
	('skvoš', 'squash', FALSE),
	('slalom', 'slalom', TRUE),
	('smuk', 'smuk', TRUE),
	('smučanje', 'skiing', TRUE),
	('smučanje in zimski športi', 'skiing and winter sports', FALSE),
	('smučarski skoki', 'ski jumping', TRUE),
	('softball', 'softball', FALSE),
	('streljanje', 'shooting', TRUE),
	('sumo', 'sumo', FALSE),
	('superveleslalom', 'super giant slalom', TRUE),
	('surfanje', 'surfing', FALSE),
	('suvanje krogle', 'pushing the ball', TRUE),
	('taekwondo', 'taekwondo', FALSE),
	('tek na dolge proge', 'running long distances', FALSE),
	('tek na smučeh', 'cross-country skiing', TRUE),
	('tek na srednje proge', 'only on the middle lanes', FALSE),
	('tek čez ovire', 'running over obstacles', TRUE),
	('teki', 'teki', FALSE),
	('tekma kamel', 'camel match', FALSE),
	('telemark smučanje', 'telemark skiing', FALSE),
	('tenis', 'tennis', TRUE),
	('trampolin', 'trampoline', FALSE),
	('triatlon', 'triathlon', TRUE),
	('troskok', 'troskok', TRUE),
	('turno smučanje', 'ski touring', FALSE),
	('ultimate frizbi', 'ultimate frisbee', FALSE),
	('vaterpolo', 'water polo', TRUE),
	('veleslalom', 'giant slalom', TRUE),
	('vertikalno rolkanje', 'vertical skateboarding', FALSE),
	('vodni športi', 'water sports', FALSE),
	('zunanji športi', 'outdoor sports', FALSE),
	('športi moči', 'power sports', FALSE),
	('športi s tarčami', 'target sports', FALSE),
	('športi z loparji', 'racket sports', FALSE),
	('športi z živalmi', 'animal sports', FALSE),
	('športna akrobatika', 'sports acrobatics', FALSE),
	('športna gimnastika', 'gymnastics', FALSE),
	('športno plezanje', 'sport climbing', TRUE),
	('šprint', 'sprint', FALSE);
