INSERT INTO domain_secondary (name_sl, name_en, approved)
VALUES
  ('Aerodinamika', 'Aerodynamics', TRUE),
  ('Akustika', 'Acustics', TRUE),
  ('Algebra', 'Algebra', TRUE),
  ('Algoritmi', 'Algorithms', TRUE),
  ('Alpinizem', 'Mountain climbing', TRUE),
  ('Alternativno zdravljenje', 'Alternative medicine', TRUE),
  ('Analizna kemija', 'Analytical chemistry', TRUE),
  ('Anatomija', 'Anatomy', TRUE),
  ('Anesteziologija', 'Anesthesiology', TRUE),
  ('Anorganska kemija', 'Inorganic chemistry', TRUE),
  ('Antična mitologija', 'Ancient mythology', TRUE),
  ('Aritmetika', 'Arithemetics', TRUE),
  ('Atletika', 'Athletics', TRUE),
  ('Atomska fizika', 'Atomic physics', TRUE),
  ('Avtomatika', 'Automatics', TRUE),
  ('Avtomobilizem', 'Motorsport', TRUE),
  ('Avtorsko pravo', 'Copyright law', TRUE),
  ('Babištvo', 'Midwifery', TRUE),
  ('Badminton', 'Badminton', TRUE),
  ('Balet', 'Ballet', TRUE),
  ('Balonarstvo', 'Ballooning', TRUE),
  ('Bančni sistem', 'Banking system', TRUE),
  ('Baseball', 'Baseball', TRUE),
  ('Besediloslovje', 'Text linguistics', TRUE),
  ('Biatlon', 'Biathlon', TRUE),
  ('Biljard', 'Billiard', TRUE),
  ('Biodinamika', 'Biodynamics', TRUE),
  ('Bioetika', 'Bioethics', TRUE),
  ('Bolezni', 'Diseases', TRUE),
  ('Borilni športi', 'Martial arts', TRUE),
  ('Budizem', 'Buddhism', TRUE),
  ('Cerkvena glasba', 'Church music', TRUE),
  ('Cerkveno pravo', 'Ecclesiastical law', TRUE),
  ('Cestni promet', 'Road traffic', TRUE),
  ('Civilna zaščita', 'Civil protection service', TRUE),
  ('Civilno pravo', 'Civil law', TRUE),
  ('Časopisi', 'Journals', TRUE),
  ('Čevljarstvo', 'Shoemaking', TRUE),
  ('Čipkarstvo', 'Lacemaking', TRUE),
  ('Členonožci', 'Arthropod', TRUE),
  ('Čutno zaznavanje', 'Sensory perception', TRUE),
  ('Daljnovodi', 'Transmission lines', TRUE),
  ('Davčno pravo', 'Tax law', TRUE),
  ('Davki in carine', 'Taxes and Customs', TRUE),
  ('Dedno pravo', 'Law of inheritance', TRUE),
  ('Delovno pravo', 'Labour law', TRUE),
  ('Denar, valute', 'Money, currencies', TRUE),
  ('Dentalna medicina', 'Dental medicine', TRUE),
  ('Dermatologija', 'Dermatology', TRUE),
  ('Diagnostika', 'Diagnostics', TRUE),
  ('Dialektologija', 'Dialectology', TRUE),
  ('Dietetika', 'Dietetics', TRUE),
  ('Digitalizacija', 'Digitalization', TRUE),
  ('Digitalna fotografija', 'Digital photograpy', TRUE),
  ('Dinamika tekočin', 'Fluid dynamics', TRUE),
  ('Diplomacija', 'Diplomacy', TRUE),
  ('Divje živali', 'Wildlife', TRUE),
  ('Domače živali', 'Domesticated animals', TRUE),
  ('Drsanje', 'Skating', TRUE),
  ('Družinsko pravo', 'Family law', TRUE),
  ('Duševni razvoj', 'Mental development', TRUE),
  ('Duševno zdravje', 'Mental health', TRUE),
  ('Dvoživke', 'Amphibian', TRUE),
  ('Ekološka pridelava', 'Organic growing', TRUE),
  ('Ekosistemi', 'Ecosystems', TRUE),
  ('Eksperimentalna kemija', 'Experimental chemistry', TRUE),
  ('Elektrarne', 'Power plant', TRUE),
  ('Električna energija', 'Electric power', TRUE),
  ('Električna mobilnost', 'Electric mobility', TRUE),
  ('Elektrika', 'Electricity', TRUE),
  ('Elektroenergetski sistemi', 'Electricity system', TRUE),
  ('Elektronika', 'Electronics', TRUE),
  ('Etimologija', 'Ethymology', TRUE),
  ('Evolucija', 'Evolution', TRUE),
  ('Farmacevtska biologija', 'Pharmaceutical biology', TRUE),
  ('Farmacevtska kemija', 'Pharmaceutical chemistry', TRUE),
  ('Farmacevtska tehnologija', 'Pharmaceutical technology', TRUE),
  ('Farmakologija', 'Pharmacology', TRUE),
  ('Filozofija prava', 'Philosophy of law', TRUE),
  ('Finančno pravo', 'Finance law', TRUE),
  ('Fitomedicina', 'Phytomedicine', TRUE),
  ('Fizikalna kemija', 'Physical chemistry', TRUE),
  ('Fiziologija', 'Phisiology', TRUE),
  ('Fiziologija rastlin', 'Plant physiology', TRUE),
  ('Fluidna tehnika', 'Fluid power equipment', TRUE),
  ('Fonetika', 'Phonetics', TRUE),
  ('Formula 1', 'Formula 1', TRUE),
  ('Fotografske tehnike', 'Photographic Techniques', TRUE),
  ('Fotogrametrija', 'Photogrammetry', TRUE),
  ('Frazeologija', 'Phraseology', TRUE),
  ('Frizerstvo', 'Hair dressing', TRUE),
  ('Gasilstvo', 'Firefighting', TRUE),
  ('Gastronomija', 'Gastronomy', TRUE),
  ('Genetika', 'Genetics', TRUE),
  ('Genski inženiring', 'Genetic engineering', TRUE),
  ('Geodetske mreže', 'Geodesic grids', TRUE),
  ('Geometrija', 'Geometry', TRUE),
  ('Gimnastika', 'Gymnastics', TRUE),
  ('Ginekologija', 'Gynecology', TRUE),
  ('Glodalci', 'Rodentia', TRUE),
  ('Golf', 'Golf', TRUE),
  ('Gospodarske družbe', 'Companies and corporations', TRUE),
  ('Gospodarsko pravo', 'Commercial law', TRUE),
  ('Grafika', 'Graphics', TRUE),
  ('Hidravlika', 'Hydraulics', TRUE),
  ('Higiena', 'Hygiene', TRUE),
  ('Hinduizem', 'Hinduism', TRUE),
  ('Hokej na ledu', 'Ice hockey', TRUE),
  ('Hokej na travi', 'Field hockey', TRUE),
  ('Humana ekologija', 'Human ecology', TRUE),
  ('Humanitarno pravo', 'Humanitarian law', TRUE),
  ('Industrija', 'Industry', TRUE),
  ('Infrastruktura', 'Infrastructure', TRUE),
  ('Inšpekcija', 'Inspection', TRUE),
  ('Inteligentni sistemi', 'Intelligent Systems', TRUE),
  ('Interna medicina', 'Internal medicine', TRUE),
  ('Internet', 'Internet', TRUE),
  ('Islam', 'Islam', TRUE),
  ('Jadranje', 'Sailing', TRUE),
  ('Jahanje', 'Riding', TRUE),
  ('Jamarstvo', 'Caving', TRUE),
  ('Jamstvo', 'Surety, guarentee', TRUE),
  ('Javne finance', 'Public finance', TRUE),
  ('Javni promet', 'Public traffic', TRUE),
  ('Javno zdravje', 'Public health', TRUE),
  ('Jazz, blues', 'Jazz, blues', TRUE),
  ('Jeklarstvo', 'Steel industry', TRUE),
  ('Jezikovno modeliranje', 'Language modelling', TRUE),
  ('Judovstvo', 'Judaism', TRUE),
  ('Kajak, kanu', 'Kayak, canoe', TRUE),
  ('Kamnoseštvo', 'Stone-cutting', TRUE),
  ('Kartiranje', 'Mapping', TRUE),
  ('Kartografske projekcije', 'Geographical projection', TRUE),
  ('Kazensko pravo', 'Criminal law', TRUE),
  ('Kegljanje', 'Ninepin bowling', TRUE),
  ('Kibernetika', 'Cybernetics', TRUE),
  ('Kibernetsko in informacijsko delovanje ', 'Cyber and information operations', TRUE),
  ('Kiparstvo', 'Sculpture', TRUE),
  ('Kirurgija', 'Surgery', TRUE),
  ('Klinična farmacija', 'Clinical pharmacy', TRUE),
  ('Klinična psihologija', 'Clinical psychology', TRUE),
  ('Kolesarjenje', 'Cycling', TRUE),
  ('Komorna glasba', 'Chamber music', TRUE),
  ('Konfucionizem', 'Confucianism', TRUE),
  ('Konkurenčno pravo', 'Competition law', TRUE),
  ('Konservatorstvo in restavratorstvo', 'Conservation and restoration', TRUE),
  ('Konstrukcije', 'Constructions', TRUE),
  ('Konzerviranje', 'Preservation', TRUE),
  ('Kopenska vojska ', 'Army', TRUE),
  ('Korpusno jezikoslovje', 'Corpus linguistics', TRUE),
  ('Košarka', 'Basketball', TRUE),
  ('Kovaštvo', 'Blacksmithery', TRUE),
  ('Kozmetika', 'Cosmetics', TRUE),
  ('Kriptovalute', 'Cryptocurrency', TRUE),
  ('Kristalografija', 'Crystalography', TRUE),
  ('Krojenje in šivanje', 'Dressmaking', TRUE),
  ('Krščanstvo', 'Christianity', TRUE),
  ('Krvodajalstvo', 'Blood donation', TRUE),
  ('Laserji', 'Lasers', TRUE),
  ('Lekarništvo', 'Pharmacy', TRUE),
  ('Lekiskologija', 'Lexicology', TRUE),
  ('Literarno prevajanje', 'Literary translation', TRUE),
  ('Ljudska glasba', 'Folk music', TRUE),
  ('Ljudsko pripovedništvo', 'Fairy and folk tales', TRUE),
  ('Lokalne oblasti', 'Local governement', TRUE),
  ('Lokostrelstvo', 'Archery', TRUE),
  ('Lončarstvo', 'Pottery', TRUE),
  ('Lov', 'Hunting', TRUE),
  ('Lutkarstvo', 'Puppetry', TRUE),
  ('Male živali', 'Small animals', TRUE),
  ('Marketing', 'Marketing', TRUE),
  ('Matematična analiza', 'Mathematical analysis', TRUE),
  ('Matematična logika', 'Mathematical logic', TRUE),
  ('Matematična statistika', 'Mathematical statistics', TRUE),
  ('Medicinska sociologija', 'Medical sociology', TRUE),
  ('Medicinski pripomočki', 'Medical devices', TRUE),
  ('Mednarodno pravo', 'International law', TRUE),
  ('Mehanika', 'Mechanics', TRUE),
  ('Mehatronika', 'Mechatronics', TRUE),
  ('Mehkužci', 'Mollusca', TRUE),
  ('Merilni instrumenti', 'Measuring instruments', TRUE),
  ('Mikrodelci', 'Ultra-fine particles', TRUE),
  ('Mineralogija', 'Mineralogy', TRUE),
  ('Mizarstvo', 'Joinery', TRUE),
  ('Mobilne naprave', 'Mobile devices', TRUE),
  ('Modno oblikovanje', 'Fashion design', TRUE),
  ('Mostovi', 'Bridges', TRUE),
  ('Motociklizem', 'Motorcycling', TRUE),
  ('Motorna vozila', 'Motor vehicles', TRUE),
  ('Naftni derivati', 'Petroleum derivatives', TRUE),
  ('Nakit', 'Jewellery', TRUE),
  ('Namizne igre', 'Tabletop games', TRUE),
  ('Namizni tenis', 'Table tennis', TRUE),
  ('Naravne nesreče', 'Natural disasters', TRUE),
  ('Naravne znamenitosti', 'Natural sites of special interest', TRUE),
  ('Narodnozabavna glasba', 'Pop folk music', TRUE),
  ('Neformalno izobraževanje', 'Nonformal learning', TRUE),
  ('Nefrologija', 'Nephrology', TRUE),
  ('Nega telesa', 'Body care', TRUE),
  ('Nevronske mreže', 'Neural network', TRUE),
  ('Nogomet', 'Football', TRUE),
  ('Noše', 'Costumes', TRUE),
  ('Notranja politika', 'Domestic policy', TRUE),
  ('Nova duhovna gibanja', 'New Age', TRUE),
  ('Numerične metode', 'Numerical methods', TRUE),
  ('Numizmatika', 'Numismatics', TRUE),
  ('Običaji', 'Folk traditon', TRUE),
  ('Oblačila', 'Clothing', TRUE),
  ('Obligacijsko pravo', 'Obligation law', TRUE),
  ('Obnovljivi viri energije', 'Renewable energy sources', TRUE),
  ('Obveščevalno-varnostno delovanje ', 'Military intelligence', TRUE),
  ('Odbojka', 'Volleyball', TRUE),
  ('Odprti dostop', 'Open access', TRUE),
  ('Odškodninsko pravo', 'Tort Law', TRUE),
  ('Oftalmologija', 'Ophthalmology', TRUE),
  ('Oglarstvo', 'Charcoal making', TRUE),
  ('Oglaševanje', 'Advertising', TRUE),
  ('Okoljsko pravo', 'Environmental law', TRUE),
  ('Okrasne rastline', 'Ornamental plants', TRUE),
  ('Opera', 'Opera', TRUE),
  ('Operacijski sistemi', 'Operating system', TRUE),
  ('Optika', 'Optycs', TRUE),
  ('Organizacijska psihologija', 'Organisational psychology', TRUE),
  ('Organska kemija', 'Organic chemistry', TRUE),
  ('Orientacija', 'Orientation', TRUE),
  ('Ortopedija', 'Orthopedics', TRUE),
  ('Osnovno šolstvo', 'Basic education', TRUE),
  ('Padalstvo', 'Parachuting', TRUE),
  ('Pajki', 'Araneae', TRUE),
  ('Paliativna oskrba', 'Palliative care', TRUE),
  ('Parapsihologija', 'Parapsychology', TRUE),
  ('Parlament', 'Parliament', TRUE),
  ('Pasme', 'Breeds', TRUE),
  ('Patologija', 'Pathology', TRUE),
  ('Periferne naprave', 'Peripheral devices', TRUE),
  ('Planinstvo', 'Hiking', TRUE),
  ('Plavanje', 'Swimming', TRUE),
  ('Plazilci', 'Reptilia ', TRUE),
  ('Pletilstvo', 'Knitting', TRUE),
  ('Plezanje', 'Climbing', TRUE),
  ('Podatkovne baze', 'Databases', TRUE),
  ('Podatkovno rudarjenje', 'Data mining', TRUE),
  ('Podjetništvo', 'Entrepreneurship', TRUE),
  ('Pohodništvo', 'Trekking', TRUE),
  ('Poklicno izobraževanje', 'Vocational education', TRUE),
  ('Policija', 'Police', TRUE),
  ('Politične stranke', 'Political parties', TRUE),
  ('Politični sistemi', 'Political systems', TRUE),
  ('Poljedelstvo', 'Agriculture', TRUE),
  ('Pomorski promet', 'Maritime traffic', TRUE),
  ('Pomorsko pravo', 'Maritime law', TRUE),
  ('Pop, rock glasba', 'Pop, rock music', TRUE),
  ('Potapljanje', 'Diving', TRUE),
  ('Požari', 'Fires', TRUE),
  ('Pragmatika', 'Pragmatics', TRUE),
  ('Pravo EU', 'EU law', TRUE),
  ('Pravopis', 'Ortography', TRUE),
  ('Pravorečje', 'Orthoepy ', TRUE),
  ('Prazniki', 'Holidays and feasts', TRUE),
  ('Predori', 'Tunnels', TRUE),
  ('Predšolska vzgoja', 'Preschool education', TRUE),
  ('Procesno pravo', 'Procedural law', TRUE),
  ('Procesno strojništvo', 'Process engineering', TRUE),
  ('Procesorji', 'Processors', TRUE),
  ('Programiranje', 'Programming', TRUE),
  ('Programska oprema', 'Software', TRUE),
  ('Programski jeziki', 'Programming languages', TRUE),
  ('Promocija zdravja', 'Health promotion', TRUE),
  ('Prostorski razvoj', 'Spatial development', TRUE),
  ('Prostorsko planiranje', 'Spatial planning', TRUE),
  ('Prostorsko urejanje', 'Site planning', TRUE),
  ('Protozoologija', 'Protozoology', TRUE),
  ('Prva pomoč', 'First aid', TRUE),
  ('Prvo posredovanje', 'First respond', TRUE),
  ('Psihiatrija', 'Psychiatry', TRUE),
  ('Psihoterapija', 'Psychotherapy', TRUE),
  ('Ptice', 'Aves', TRUE),
  ('Računalniška grafika', 'Computer graphics', TRUE),
  ('Računalniška omrežja', 'Computer networks', TRUE),
  ('Računalniška simulacija', 'Computer simulation', TRUE),
  ('Računalniške igre', 'Computer games', TRUE),
  ('Računalniški virusi', 'Computer worms', TRUE),
  ('Radio', 'Radio', TRUE),
  ('Raki', 'Crustacea', TRUE),
  ('Rastlinske vrste', 'Plant species', TRUE),
  ('Razpoznava govora', 'Speech recognition', TRUE),
  ('Razvojna psihologija', 'Developmental psychology', TRUE),
  ('Rečni promet', 'River traffic', TRUE),
  ('Rejne živali', 'Livestock', TRUE),
  ('Rekreacija', 'Recreation', TRUE),
  ('Retorika', 'Rhetoric', TRUE),
  ('Rezbarstvo', 'Carving', TRUE),
  ('Ribe', 'Fish fauna', TRUE),
  ('Risanje', 'Drawing', TRUE),
  ('Robotika', 'Robotics', TRUE),
  ('Rokomet', 'Handball', TRUE),
  ('Sabljanje', 'Fencing', TRUE),
  ('Sadjarstvo', 'Fruit growing', TRUE),
  ('Sankanje', 'Sledding', TRUE),
  ('Seksologija', 'Sexology', TRUE),
  ('Sesalci', 'Mammalia', TRUE),
  ('Siva ekonomija', 'Grey economy', TRUE),
  ('Skladnja', 'Syntax', TRUE),
  ('Slikarstvo', 'Painting', TRUE),
  ('Smučanje', 'Skiing', TRUE),
  ('Smučarski skoki', 'Ski jumping', TRUE),
  ('Socialna antropologija', 'Social anthropology', TRUE),
  ('Socialna etika', 'Social ethics', TRUE),
  ('Socialna filozofija', 'Social philosophy', TRUE),
  ('Socialna psihologija', 'Social psychology', TRUE),
  ('Socialno pravo', 'Social security law', TRUE),
  ('Sociologija kulture', 'Sociology of culture', TRUE),
  ('Sodstvo', 'Judicial administration', TRUE),
  ('Soteskanje', 'Canyoning', TRUE),
  ('Specialna pedagogika', 'Special teaching', TRUE),
  ('Spletni mediji', 'Digital media', TRUE),
  ('Srednje šolstvo', 'Secondary education', TRUE),
  ('Stilistika', 'Stylistics', TRUE),
  ('Strelstvo', 'Shooting sports', TRUE),
  ('Strojno prevajanje', 'Machine translation', TRUE),
  ('Strojno učenje', 'Machine learning', TRUE),
  ('Stvarno pravo', 'Property law', TRUE),
  ('Svetlobna tehnika', 'Lighting engineering', TRUE),
  ('Šah', 'Chess', TRUE),
  ('Športni ribolov', 'Sport fishing', TRUE),
  ('Telekomunikacije', 'Telecommunications', TRUE),
  ('Televizija', 'Television', TRUE),
  ('Tenis', 'Tennis', TRUE),
  ('Teorija števil', 'Number theory', TRUE),
  ('Terminologija', 'Terminology', TRUE),
  ('Termodinamika', 'Thermodynamics', TRUE),
  ('Tiskarstvo', 'Typography', TRUE),
  ('Tiskovne agencije', 'Press agencies', TRUE),
  ('Tkalstvo', 'Weaving', TRUE),
  ('Toksikologija', 'Toxicology', TRUE),
  ('Tolmačenje', 'Interpreting', TRUE),
  ('Toplota', 'Heat', TRUE),
  ('Topografija', 'Topography', TRUE),
  ('Transformatorji', 'Transformers', TRUE),
  ('Transportno pravo', 'Tranprot law', TRUE),
  ('Trg dela', 'Labour market', TRUE),
  ('Tržna ekonomija', 'Market economy', TRUE),
  ('Ulično gledališče', 'Street theatre', TRUE),
  ('Umetna inteligenca', 'Artificial intelligence', TRUE),
  ('Uporabna matematika', 'Applied mathematics', TRUE),
  ('Uporabna psihologija', 'Applied psychology', TRUE),
  ('Uporabna umetnost', 'Aplied arts', TRUE),
  ('Uporabniški vmesniki', 'User interfaces', TRUE),
  ('Upravno pravo', 'Administrative law', TRUE),
  ('Urbani prostor', 'Urban space', TRUE),
  ('Usnjarstvo', 'Leathermaking', TRUE),
  ('Ustavno pravo', 'Constitutional law', TRUE),
  ('Varjenje', 'Welding', TRUE),
  ('Varnost hrane', 'Food safety', TRUE),
  ('Varstvo tal', 'Soil protection', TRUE),
  ('Varstvo voda', 'Water protection', TRUE),
  ('Vaterpolo', 'Waterpolo', TRUE),
  ('Vesoljsko pravo', 'Space law', TRUE),
  ('Vinogradništvo', 'Wine growing', TRUE),
  ('Visoko šolstvo', 'Higher education', TRUE),
  ('Vlada in ministrstva', 'Government and ministries', TRUE),
  ('Vojaška mornarica ', 'Navy', TRUE),
  ('Vojaške operacije ', 'Military operations', TRUE),
  ('Vojaški kadri in logistika ', 'Military manpower and logistics', TRUE),
  ('Vojaško letalstvo ', 'Air foces', TRUE),
  ('Vojno pravo', 'Law of war', TRUE),
  ('Volitve', 'Elections', TRUE),
  ('Vretenčarji', 'Vertebrata', TRUE),
  ('Vrtičkarstvo', 'Gardening', TRUE),
  ('Vrtnarstvo', 'Commercial gardening', TRUE),
  ('Zavarovalno pravo', 'Insurance law', TRUE),
  ('Zborovska glasba', 'Choir music', TRUE),
  ('Zdravstvena nega', 'Nursing', TRUE),
  ('Zdravstvena oskrba', 'Nursing care', TRUE),
  ('Zelenjadarstvo', 'Vegetable growing', TRUE),
  ('Zeliščarstvo', 'Herbs growing', TRUE),
  ('Zemeljski plin', 'Natural gas', TRUE),
  ('Zgodovinsko jezikoslovje', 'Historical Linguistics', TRUE),
  ('Zlatarstvo', 'Goldsmithery', TRUE),
  ('Zračni promet', 'Air traffic', TRUE),
  ('Zunanja politika', 'Foreign policy', TRUE),
  ('Zveri', 'Carnivora', TRUE),
  ('Zvonarstvo', 'Bellfounding', TRUE),
  ('Železarstvo', 'Iron industry', TRUE),
  ('Železniški promet', 'Rail traffic', TRUE),
  ('Živilske tehnologije', 'Food technology', TRUE),
  ('Žuželke', 'Insecta', TRUE);
