CREATE TABLE extraction_oss_document_types (
  id SMALLINT PRIMARY KEY,
  name_sl VARCHAR NOT NULL UNIQUE,
  name_en VARCHAR NOT NULL UNIQUE
);

INSERT INTO extraction_oss_document_types (id, name_sl, name_en)
VALUES
  (101, 'Izvirni znanstveni članek', 'Original Scientific Article'),
  (102, 'Pregledni znanstveni članek', 'Review Article'),
  (103, 'Kratki znanstveni prispevek', 'Short Scientific Article'),
  (104, 'Strokovni članek', 'Professional Article'),
  (105, 'Poljudni članek', 'Popular Article'),
  (106, 'Objavljeni znanstveni prispevek na konferenci (vabljeno predavanje)', 'Published Scientific Conference Contribution (invited lecture)'),
  (107, 'Objavljeni strokovni prispevek na konferenci (vabljeno predavanje)', 'Published Professional Conference Contribution (invited lecture)'),
  (108, 'Objavljeni znanstveni prispevek na konferenci', 'Published Scientific Conference Contribution'),
  (109, 'Objavljeni strokovni prispevek na konferenci', 'Published Professional Conference Contribution'),
  (110, 'Objavljeni povzetek znanstvenega prispevka na konferenci (vabljeno predavanje)', 'Published Scientific Conference Contribution Abstract (invited lecture)'),
  (112, 'Objavljeni povzetek znanstvenega prispevka na konferenci', 'Published Scientific Conference Contribution Abstract'),
  (113, 'Objavljeni povzetek strokovnega prispevka na konferenci', 'Published Professional Conference Contribution Abstract'),
  (116, 'Samostojni znanstveni sestavek ali poglavje v monografski publikaciji', 'Independent Scientific Component Part or a Chapter in a Monograph'),
  (117, 'Samostojni strokovni sestavek ali poglavje v monografski publikaciji', 'Independent Professional Component Part or a Chapter in a Monograph'),
  (118, 'Geslo – sestavek v enciklopediji, leksikonu, slovarju...', 'Encyclopaedia, Lexicon, Dictionary (and the like) Entry'),
  (119, 'Recenzija, prikaz knjige, kritika', 'Review, Book Review, Critique'),
  (120, 'Predgovor, spremna beseda', 'Preface, Afterword'),
  (121, 'Polemika, diskusijski prispevek', 'Polemic, Discussion'),
  (122, 'Intervju', 'Interview'),
  (123, 'Umetniški sestavek', 'Artistic Component Part'),
  (124, 'Bibliografija, kazalo ipd.', 'Bibliography, Index, etc.'),
  (125, 'Drugi članki ali sestavki', 'Other Component Parts'),
  (201, 'Znanstvena monografija', 'Scientific Monograph'),
  (202, 'Strokovna monografija', 'Professional Monograph'),
  (203, 'Univerzitetni, visokošolski ali višješolski učbenik z recenzijo', 'Reviewed University, Higher Education or Higher Vocational Education Textbook'),
  (204, 'Srednješolski, osnovnošolski ali drugi učbenik z recenzijo', 'Reviewed Secondary and Primary School Textbook or Other Textbook'),
  (205, 'Video in druga učna gradiva', 'Videolectures and teaching material'),
  (206, 'Enciklopedija, slovar, leksikon, priročnik, atlas, zemljevid', 'Encyclopaedia, Dictionary, Lexicon, Manual, Atlas, Map'),
  (207, 'Bibliografija', 'Bibliography'),
  (208, 'Doktorska disertacija', 'Doctoral Dissertation'),
  (209, 'Magistrsko delo', 'Master''s Thesis'),
  (210, 'Specialistično delo', 'Specialist Thesis'),
  (211, 'Diplomsko delo', 'Undergraduate Thesis'),
  (212, 'Končno poročilo o rezultatih raziskav', 'Final Research Report'),
  (213, 'Elaborat, predštudija, študija', 'Treatise, Preliminary Study, Study'),
  (214, 'Projektna dokumentacija (idejni projekt, izvedbeni projekt)', 'Project Documentation (preliminary design, working design)'),
  (215, 'Izvedensko mnenje, arbitražna odločba', 'Expertise, Arbitration Decision'),
  (216, 'Umetniško delo', 'Artistic Work'),
  (217, 'Katalog razstave', 'Exhibition Catalogue'),
  (218, 'Raziskovalni ali dokumentarni film, zvočni ali video posnetek', 'Scientific or Documentary Film, Sound or Video Recording'),
  (219, 'Radijska ali televizijska oddaja', 'Radio or Television Broadcast'),
  (220, 'Raziskovalni podatki', 'Research Data'),
  (221, 'Programska oprema', 'Software'),
  (222, 'Nova sorta', 'New variety'),
  (223, 'Patentna prijava', 'Patent Application'),
  (224, 'Patent', 'Patent'),
  (225, 'Druge monografije in druga zaključena dela', 'Other Monographs and Other Completed Works'),
  (227, 'Znanstveni terminološki slovar, enciklopedija ali tematski leksikon', 'Znanstveni terminološki slovar, enciklopedija ali tematski leksikon'),
  (230, 'Zbornik strokovnih ali nerecenziranih znanstvenih prispevkov na konferenci', 'Proceedings of Professional or Unreviewed Scientific Conference Contributions'),
  (231, 'Zbornik recenziranih znanstvenih prispevkov na mednarodni ali tuji konferenci', 'Proceedings of Peer-Reviewed Scientific Conference Contributions (international and foreign conferences)'),
  (232, 'Zbornik recenziranih znanstvenih prispevkov na domači konferenci', 'Proceedings of Peer-Reviewed Scientific Conference Contributions (domestic conferences)'),
  (310, 'Umetniška poustvaritev', 'Artistic Performance'),
  (311, 'Radijski ali TV dogodek', 'Radio or Television Event'),
  (312, 'Razstava', 'Exhibition'),
  (313, 'Organiziranje znanstvenih in strokovnih sestankov', 'Organizing scientific and professional meetings'),
  (314, 'Predavanje na tuji univerzi', 'Invited Lecture at Foreign University'),
  (315, 'Prispevek na konferenci brez natisa', 'Unpublished Conference Contribution'),
  (316, 'Vabljeno predavanje na konferenci brez natisa', 'Unpublished Invited Conference Lecture'),
  (320, 'Druga dela', 'Other Works'),
  (325, 'Druga izvedena dela', 'Other Performed Works');
